import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Toaster } from "@/components/ui/toaster";
import Layout from "@/components/Layout";
import { cookies } from "next/headers";
import AuthProvider from "./context/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const layout = cookies().get("react-resizable-panels:layout");
    const collapsed = cookies().get("react-resizable-panels:collapsed");
    const defaultLayout =
        layout && layout.value && isJsonString(layout.value)
            ? JSON.parse(layout.value)
            : undefined;
    const defaultCollapsed =
        collapsed && collapsed.value && isJsonString(collapsed.value)
            ? JSON.parse(collapsed.value)
            : undefined;

    return (
        <html lang='en'>
            <body className={`${inter.className} h-screen`}>
                <AuthProvider>
                    <Layout
                        defaultLayout={defaultLayout}
                        defaultCollapsed={defaultCollapsed}
                        navCollapsedSize={4}>
                        {children}
                    </Layout>
                </AuthProvider>
                <Toaster />
            </body>
        </html>
    );
}

function isJsonString(str: string) {
    try {
        JSON.parse(str);
    } catch (e) {
        return false;
    }
    return true;
}
